### ISSUE TITLE
Lesson 5: Chapter 12: SafeMath Part4

### ISSUE THREAD

**Issue by hurricanenara** [loomnetwork/cryptozombie-lessons#538] opened 2021-08-24 00:33 UTC
Test fails when `using SafeMath for uint256` on line 8, but passes when removed. It seemed odd that throughout the first three parts, we were importing SafeMath `using` to pass tests, and having to do the opposite to pass part 4. 

![image](https://user-images.githubusercontent.com/58568960/130536774-3c93aafe-6f1a-4925-9478-6b385f1c7564.png)

**Comment by andreipope** [comment] 2022-02-25 07:24
@hurricanenara Thanks! We cannot reproduce this so I'm closing the issue.

**Closed by andreipope** 2022-02-25 07:24 UTC
